language: java
jdk:
  - oraclejdk8
  - oraclejdk9
env:
  - TERM=dumb
after_success:
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew clean jar bintray -x test
branches:
  only:
    - master

    